language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: EMGX/gAAt0rmlANTPUC45uMN/ZbpenXWJWMkKsbW+RD6x36XTgfH0tBf8Q2Vv252DCEl1nf1c91SEGAXO6Z7Ys/OVRDTVeTXojsO0NZ0eux7lakZwOPor2fQP5OVyEx144VB/7mt7xwqjayZTqAnQMceJ8pPPaI4SIbzcITG9AufaTOPUq8GOW8y/Y9Ur6+vb4vMugjxiDjTX1g4EJ783nmDtG43OEEc/KCm8DQwf6JkJRu6deO8LIL53jAgSnlWOfvb65NJzU0JLVq3ef0kICpWjMu5KrLGg25pNfklvxLlTxA+VhbWTROYVCYaE1HOz+KM5aum3ch35qJPEqgWxrK8EsZzsuJXRCLNzqi0hdB6ztSkEvw1m6kzTXX4Hh+ffx4xDQcXf4Hl1O7QZ0BRtR6WGS83ov5GWs5FxM3EUPdLonWSghONgPIUz7AnO+kqZ9hjBi2XZV3atXJA+tHEdbaBOmsbWIX+Sj+TJ3A88p/3WqaPh+d6DKa2uy2dQ0kqHv2GuqrUBlBDfvtWvTjzo7toOzgWGMAGuSdDpg6XkEv2ImbrUyFIxwP9Xd92+CQKBLWmYEp3ACSgbQcYVN3QGjE+2VClqH2/mtbJta49lm/5XdqU54MJZJVFZ7hF5RdJp4spXsLvNNnzMQb7q3XUi0l1wDSifaRBaLNWnMX9iNg=
  app: thawing-ravine-79238
  on:
    repo: jorgerodriguez434/chef-app-api
